apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pipelines.herd.suse.com
  labels:
    app.kubernetes.io/name: herd
    app.kubernetes.io/component: crd
spec:
  group: herd.suse.com
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - env
            - targets
            - steps
            properties:
              env:
                type: string
                description: "Environment name (e.g., dev, staging, prod)"
              targets:
                type: object
                required: [clusterIds]
                properties:
                  clusterIds:
                    type: array
                    description: "Explicit list of cluster IDs"
                    items:
                      type: string
              steps:
                type: array
                description: "List of pipeline steps to execute"
                items:
                  type: object
                  required:
                  - name
                  - type
                  - config
                  properties:
                    name:
                      type: string
                      description: "Name of the pipeline step"
                    type:
                      type: string
                      enum:
                      - ingestion
                      - vector-db
                      - llm
                      - service
                      description: "Type of pipeline step"
                    config:
                      type: object
                      description: "Step-specific configuration parameters"
                      x-kubernetes-preserve-unknown-fields: true
                    dependsOn:
                      type: array
                      description: "List of steps this step depends on"
                      items:
                        type: string
                    timeout:
                      type: string
                      description: "Timeout for step execution"
                      default: "10m"
                    retries:
                      type: integer
                      description: "Number of retries on failure"
                      default: 3
                      minimum: 0
                      maximum: 10
              security:
                type: boolean
                description: "Enable security scanning for pipeline components"
                default: false
              observability:
                type: boolean
                description: "Enable observability monitoring for pipeline"
                default: false
          status:
            type: object
            properties:
              phase:
                type: string
                enum:
                - Pending
                - Running
                - Completed
                - Failed
                description: "Current phase of the pipeline execution"
              message:
                type: string
                description: "Human-readable message about the current status"
              observedGeneration:
                type: integer
                format: int64
                description: "The generation observed by the controller"
              conditions:
                type: array
                description: "Conditions represent the latest available observations"
                items:
                  type: object
                  required:
                  - type
                  - status
                  properties:
                    type:
                      type: string
                      description: "Type of condition"
                    status:
                      type: string
                      enum:
                      - "True"
                      - "False"
                      - "Unknown"
                      description: "Status of the condition"
                    reason:
                      type: string
                      description: "Reason for the condition's last transition"
                    message:
                      type: string
                      description: "Human-readable message about the transition"
                    lastTransitionTime:
                      type: string
                      format: date-time
                      description: "Last time the condition transitioned"
              stepStatus:
                type: array
                description: "Status of individual pipeline steps"
                items:
                  type: object
                  properties:
                    stepName:
                      type: string
                    stepType:
                      type: string
                    phase:
                      type: string
                      enum:
                      - Pending
                      - Running
                      - Completed
                      - Failed
                      - Skipped
                    message:
                      type: string
                    lastUpdated:
                      type: string
                      format: date-time
                    retryCount:
                      type: integer
                    executionTime:
                      type: string
                      description: "Duration of step execution"
              targetClusters:
                type: array
                description: "Resolved target cluster IDs"
                items:
                  type: string
              lastReconcileTime:
                type: string
                format: date-time
                description: "Time of last reconciliation"
    additionalPrinterColumns:
    - name: Phase
      type: string
      description: "Current phase"
      jsonPath: .status.phase
    - name: Steps
      type: integer
      description: "Number of steps"
      jsonPath: .spec.steps[*]
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp
    subresources:
      status: {}
  scope: Namespaced
  names:
    plural: pipelines
    singular: pipeline
    kind: Pipeline
    shortNames:
    - pl
